lanugage: go
go:
    - 1.8.x
    - master
go_import_path: ./
install:
    - go get github.com/astaxie/beego
    - go get github.com/smartystreets/goconvey/convey
script: 
    - ls
    - go test ./tests
