lanugage: go
go:
    - 1.8.3
    - master
install:
    - export GOPATH="${TRAVIS_BUILD_DIR}/fionser:$GOPATH"
    - go get github.com/astaxie/beego
    - go get github.com/smartystreets/goconvey/convey
script: 
    - go test ./tests
